### ISSUE TITLE
Error when load

### ISSUE THREAD

**Issue by wesleyfang** [smart-on-fhir/growth-chart-app#18]
The page says: Loading error. See console for details and the console write:
No 'state' parameter found in authorization response.

**Comment by vlad-ignatov** [comment]
This typically means that your SMART session (1 hour duration) has expired and you just need to re-launch the app. If you are using a tool like this https://fhir-dstu2.smarthealthit.org/ refresh it, sign in if needed and launch again.

**Comment by ewheeler** [comment]
@vlad-ignatov i'm getting the same error when running for the first time after cloning per the deployment instructions in the readme

**Comment by vlad-ignatov** [comment]
Which deployment instructions are you referring to? Can you launch other apps?

**Comment by vlad-ignatov** [comment]
Here I am starting it:

1. From a console in the project directory, execute `npm install`.
2. Edit `launch.html` and set the "client_id" on line 10 to "my_web_app".
3. Setup a webserver like Apache or NginX so that http://localhost:8000/fhir-app/ serves the project directory.
4. Open https://fhir-dstu2.smarthealthit.org/, login and select a patient (Allen Vitalis would be fine).
5. Click the "My Web App" button or setup the last section to look like the image below and click "Custom App" (the full URL there is http://localhost:8000/fhir-app/launch.html).
 
<img width="319" alt="screen shot 2016-11-09 at 3 51 27 pm" src="https://cloud.githubusercontent.com/assets/1119082/20140559/83cbaeb6-a694-11e6-913a-10b1657003a7.png">

**Comment by ewheeler** [comment]
i'm following these instructions: https://github.com/smart-on-fhir/growth-chart-app#deploymemt

... which do not include most of the steps you mention

**Comment by vlad-ignatov** [comment]
That is correct. The issue is that these apps cannot be launched directly. Instead they require dedicated smart client to be registered first and then they can be started via tools like https://fhir-dstu2.smarthealthit.org, https://gallery.smarthealthit.org/ or https://stub.smarthealthit.org/.

I am the creator of this app and I have always started it this way. Later somebody have added that `http-server` module to make things easier but the documentation is not complete. I will fix the README and for now here are the important things you need to know:

1. When you pull the app it comes configured to use the "growth_chart" client (in the `launch.html` file). However, that is not useful because that is the public client of the app which is configured to only allow launching from https://fhir-dstu2.smarthealthit.org/apps/growth-chart/. You are supposed to create your own client at https://authorize-dstu2.smarthealthit.org/ or you can just use the default one having the "my_web_app" id  for testing.

2. If you register your own client you can use whatever launch/redirect URLs you like but if you go with the default "my_web_app" client, then you are forced to host the app at http://localhost:8000/fhir-app/

3. Using that `npm run serve` command does help a little because this way you won't have to configure apache or nginx but that will only work if you register your own client with launch_url equal to `http://localhost:8000/launch.html` and redirect_url` like:
```js
["http://localhost:8000/", "http://127.0.0.1:8000/"]
```
I hope that helps for now.

**Comment by ewheeler** [comment]
@vlad-ignatov thanks for the details. i thought this could be launched separately

**Comment by lw621** [comment]
I have some issue on launching the project pulled from the git repo.

**Comment by nschwertner** [comment]
It's a SMART app, folks. Needs to be run in context from withing a SMART environment. See http://docs.smarthealthit.org for details
